config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root to: "home#index"

  get 'shopping_cart', to: 'shopping_carts#show'
  get 'shopping_cart/add/:ticket_type_id/:amount', to: 'shopping_carts#add_ticket', defaults: { amount: 1 }
  post 'shopping_cart/add', to: 'shopping_carts#add_ticket'
  get 'shopping_cart/update/:ticket_type_id/:amount', to: 'shopping_carts#update', :defaults => { :format => 'json' }
  post 'shopping_cart/update', to: 'shopping_carts#update', :defaults => { :format => 'json' }
  get 'checkout', to: 'orders#new'

  resources :events
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :tickets
  has_one :delivery_address, inverse_of: :order
  accepts_nested_attributes_for :delivery_address



  def get_order_total()
    sum = 0
    self.tickets.each do |t|
      sum += t.ticket_type.price
    end
    sum
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order_summary = {}
    @order.tickets.each do |ticket|
      if !@order_summary.key?(ticket.ticket_type)
        @order_summary[ticket.ticket_type] = 1
      else
        @order_summary[ticket.ticket_type] += 1
      end
    end
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.delivery_address = DeliveryAddress.new

    # Get the tickets in the shopping cart
    ticket_types = helpers.shopping_cart_get_tickets()
    @required_tickets = {}

    ticket_types.each do |k,v|
      tt = TicketType.find(k)
      @required_tickets[tt] = v
    end

    # Add tickets to the order
    ticket_types.each do |k,v|
      tt = TicketType.find(k)
      v.times do |i|
        t = Ticket.new(ticket_type: tt)
        @order.tickets << t
      end
    end

  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    # Get the tickets in the shopping cart
    tickets = helpers.shopping_cart_get_tickets()

    total = 0

    # Add tickets to the order
    tickets.each do |k,v|
      tt = TicketType.find(k)
      total += tt.price * v
      v.times do |i|
        t = Ticket.new(ticket_type: tt)
        @order.tickets << t
      end
    end

    @order.user = current_user
    @order.total = total

    respond_to do |format|
      if @order.save(order_params)
        # Reset the shopping cart!
        session[:shopping_cart] = []
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        flash[:notice] = 'Failed to complete your order.'
        format.html { redirect_to action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(delivery_address_attributes: [:id, :recipient_fullname, :line1, :line2, :city, :country])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Date</th>
      <th>Number of tickets</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.id, order %></td>
        <td><%= order.created_at %></td>
        <td><%= order.tickets.length %></td>
        <td><%= order.total %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>Checkout your order!</h1>

<p>Your order contains the following tickets:</p>

<table>
  <thead>
  <tr>
    <th>Event</th>
    <th>Date</th>
    <th>Ticket Zone</th>
    <th>Price</th>
    <th>Amount</th>
  </tr>
  </thead>
  <tbody>
  <% @required_tickets.each do |k,v| %>
    <tr id="<%="details_#{k.id}_"%>">
      <td><%=k.event.name %></td>
      <td><%=k.event.start_date %></td>
      <td><%=k.ticket_zone.zone%></td>
      <td><%=k.price%></td>
      <td><%=v%></td>
    </tr>
  <% end %>
  <tr>
    <td colspan="4">
      Order total:
    </td>
    <td>
      <span id="order_total">
        <%=@order.get_order_total()%>
      </span>
    </td>
  </tr>
  </tbody>
</table>

<p>Please provide shipping details:</p>
<%=form_with(model: @order, local: true) do |form|%>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% @order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%=form.fields_for :delivery_address do |address_form| %>
    <%= address_form.label :recipient_fullname%>
    <%= address_form.text_field :recipient_fullname %>
    <%= address_form.label :line1 %>
    <%= address_form.text_field :line1 %>
    <%= address_form.label :line2 %>
    <%= address_form.text_field :line2 %>
    <%= address_form.label :city %>
    <%= address_form.text_field :city %>
    <%= address_form.label :country %>
    <%= address_form.text_field :country %>
  <% end %>
  <div class="actions">
  <%= form.submit 'Submit order' %>
  </div>
<% end %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1>Your Order, id: <%=@order.id%>, date: <%=@order.created_at%></h1>

<h3>Tickets purchased</h3>

<table>
  <thead>
  <tr>
    <th>Event</th>
    <th>Date</th>
    <th>Ticket Zone</th>
    <th>Price</th>
    <th>Amount</th>
  </tr>
  </thead>
  <tbody>
  <% @order_summary.each do |k,v| %>
    <tr>
      <td><%=k.event.name %></td>
      <td><%=k.event.start_date %></td>
      <td><%=k.ticket_zone.zone%></td>
      <td><%=k.price%></td>
      <td><%=v%></td>
    </tr>
  <% end %>
  <tr>
    <td colspan="4">
      Order total:
    </td>
    <td>
      <span id="order_total">
        <%=@order.total%>
      </span>
    </td>
  </tr>
  </tbody>
</table>

<h3>Delivery information</h3>
<table>
  <tbody>
    <tr>
      <th>
        Recipient name
      </th>
      <td>
        <%=@order.delivery_address.recipient_fullname %>
      </td>
    </tr>
    <tr>
      <th>
        Address Line 1
      </th>
      <td>
        <%=@order.delivery_address.line1 %>
      </td>
    </tr>
    <tr>
      <th>
        Address Line 2
      </th>
      <td>
        <%=@order.delivery_address.line2 %>
      </td>
    </tr>
    <tr>
      <th>
        City
      </th>
      <td>
        <%=@order.delivery_address.city %>
      </td>
    </tr>
    <tr>
      <th>
        Country
      </th>
      <td>
        <%=@order.delivery_address.country %>
      </td>
    </tr>

  </tbody>
</table>

<%= link_to 'Home', root_path %>